# Generated by Django 4.2.1 on 2023-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0002_alter_producto_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('contraseña', models.CharField(max_length=254)),
            ],
        ),
    ]
