# Generated by Django 4.2.1 on 2023-06-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
