# Generated by Django 4.2.1 on 2023-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0004_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(upload_to='ImagenesProductos/'),
        ),
    ]
